<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title>&Eacute;cesis :: Sistema para la simulaci&oacute;n de la evaluacion ECAES</title>
		<link rel="stylesheet" href="../css/reset.css" media="screen"/>
		<link rel="stylesheet" href="../css/style.css" media="screen"/>
		<script src="../jquery/jquery-1.5.js" type="text/javascript"></script>
		<script src="../js/calendar.js" type="text/javascript"></script>
		<script src="../js/calendar_navigation.js" type="text/javascript"></script>
		<script src="../js/cronevt.js" type="text/javascript"></script>
		<script type="text/javascript">
			$('document').ready(function(){
				
			});
		</script>
	</head>
	<body>
	<?php
		include_once '../../controllers/SesionController.php';
		$misesion = new SesionController();
		$misesion->sesionIniciada(1);
		$misesion->sesionTerminada();
	?>
		<div id="header-bg"></div>
		<div id="page">
			<div id="header">
				<div id="logo"></div>
				<div id="nav-bar">
					<ul>
						<li><a href="#">Crear un test</a></li>
						<li><a href="#">Cronograma</a></li>
						<li><a href="#">Mi Rendimiento</a></li>
						<li><input type="submit" name="logout" id ="logout" value="Salir"/></li>
					</ul>
				</div>
			</div>
			<div id="banner">
				<div id="image-banner"></div>
				<div id="motd"></div>
			</div>
			<div id="content" style="height: 570px;">
				<div id="login-info">
					<p><?php echo "" . $_SESSION['nombres'] . " ". $_SESSION['apellidos'] . "[estudiante]"?></p>
				</div><!-- end login-info -->
				<div id="mainsection">
					<div id="nav">
						<ul>
							<li><a class="back" href="menuestudiante.phtml">Volver al men&uacute;</a></li>
						</ul>
					</div><!-- end nav -->
					<div id="cronograma">
						<div class="tituloseccion" id="titulocron">
							<h3>Cronograma de actividades</h3>
							</div><!-- end titulocron -->
							<div id="calendar">
								<p id="p1"></p>
							</div><!-- end calendar -->
							<div id="eventos">
								<div class="tituloseccion" id="tituloevt">
									<h3>Eventos del d&iacute;a</h3>
								</div>
					
							</div>
					</div><!-- end cronograma -->
				</div><!-- end mainsection -->
			<div id="sidebar">
				<div id="resumencron">
					<p class="title">Pr&oacute;ximos eventos:</p>
					<ul>
						<li><p><span class="fecha">Mayo 6</span> Simulacro 1 sajkkjsadjksadsaj klsa klsalkd ksalkds</p></li>
						<li><p><span class="fecha">Mayo 26</span> Simulacro 2 asjdnasjdh </p></li>
						<li><p><span class="fecha">Junio 2</span> Simulacro 3 djasjdsl jsjksahd sakdsjkhda sadkshadjks </p></li>
					</ul>
				</div><!-- end resumencron -->
				<div id="resumenrendimiento">
					<p class="title">Estadísticas:</p>
					<ul>
						<li><p><span class="item">Preguntas correctas:</span> 76 / 100</p></li>
						<li><p><span class="item">Porcentaje:</span> 76%</p></li>
						<li><p><span class="item">Ranking:</span> 1°</p></li>
					</ul>
				</div><!-- end resumenrendimiento -->
			</div><!-- end sidebar -->
			</div><!-- end content -->
			<div id="footer">
				<p>&copy; 2011 Universidad de C&oacute;rdoba</p>
			</div>
		</div>
		</body>
</html>
