<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<?php
include_once '../../controllers/SesionController.php';

$con = new SesionController();
$con->login();
$con->actionsUsers();
?>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title>&Eacute;cesis :: Sistema para la simulaci&oacute;n de la evaluacion ECAES</title>
		<link rel="stylesheet" href="../css/reset.css" media="screen"/>
		<link rel="stylesheet" href="../css/style.css" media="screen"/>
		<script src="../jquery/jquery-1.5.js" type="text/javascript"></script>
		<script src="../js/usuario.js" type="text/javascript"></script>
		<script src="../js/redirecciones.js" type="text/javascript"></script>
	</head>
	<body>

		<div id="header-bg"></div>
		<div id="page">
			<div id="header">
				<div id="logo"></div>
			</div>
			<div id="banner">
				<div id="image-banner"></div>
				<div id="motd"></div>
			</div>
			<hr/>
			<div id="content" style="background-color: #3F92D2;">
				<div id="login-form">
					<form action="" method="post" action="">
					<ul>
					<li><p>Entrar al sistema</p></li>
					<li id="msgerr"></li>
					<li><input type="text" name="user" id="user" value="Nombre de usuario"/></li>
					<li><input type="password" name="pass" id="pwd" value="Contrase&ntilde;a" /></li>
					<li><input type="submit" name="entrar" id ="entrar" value="Entrar"/></li>
					<li><input class="boton_register" type="submit" name="register" id ="register" value="&#62;&#62;&#62; Regístrate &#60;&#60;&#60;"/></li>
					<li><a href="#">Recuperar datos de cuenta</a></li>
					</ul>
					</form>
				</div>
				<div id="info">
					<p class="antetitulos">Bienvenido a &eacute;cesis</p>
					<p>Écesis es una herramienta que tiene como objetivo preparar a los estudiantes 
					universitarios, que cursan el ultimo a&ntilde;o de su carrera, para las pruebas ECAES (Saber PRO) 
					por medio de la evaluación personal y la simulación de las pruebas con ayuda del docente.</p>
				</div>
			</div>
			<div id="footer">
				<p>&copy; 2011 Universidad de C&oacute;rdoba</p>
			</div>
		</div>
			</body>
</html>
