<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title>&Eacute;cesis :: Sistema para la simulaci&oacute;n de la evaluacion ECAES</title>
		<link rel="stylesheet" href="../css/reset.css" media="screen"/>
		<link rel="stylesheet" href="../css/modal.css" media="screen"/>
		<link rel="stylesheet" href="../jquery/ui/themes/jquery.ui.all.css" media="screen"/>
		<link rel="stylesheet" href="../jquery/ui/themes/jquery.ui.selectmenu.css" media="screen"/>
		<link rel="stylesheet" href="../css/style.css" media="screen"/>
		<script src="../js/usuario.js" type="text/javascript"></script>
		<script src="../js/redirecciones.js" type="text/javascript"></script>
		<script src="../jquery/jquery-1.5.js" type="text/javascript"></script>
		<script src="../jquery/ui/jquery.ui.core.js" type="text/javascript"></script>
		<script src="../jquery/ui/jquery.ui.widget.js" type="text/javascript"></script>
		<script src="../jquery/ui/jquery.ui.position.js" type="text/javascript"></script>
		<script src="../jquery/ui/jquery.ui.selectmenu.js" type="text/javascript"></script>
		<script src="../js/modaldialog.js" type="text/javascript"></script>
		<script src="../js/events.js" type="text/javascript"></script>
	</head>
	<body>
<div id="boxes">
    <div id="dialog" class="window">
    	<div id="createstform">
    		<div class="tituloseccion" id="titulotestform">
				<h3>Crear un test de pr&aacute;ctica</h3>
			</div>
		<ul>
							
								<li><p>Nombre del test de prueba:</p></li>
								<li><input name="nomtest" id="nomtest" class="text"/></li>
								<li><p>&Aacute;rea:</p></li>
								<li id="selarea"></li>
								<li><p>Asignatura:</p></li>
								<li id="selasignatura"></li>
								<li>
									<table>
										<tr>
											<td><a href="#" id="btnok"></a></td>
											<td><a href="#" class="close" id="btncancel"></a></td>
										</tr>
									</table>
								</li>
						</ul>	
			</div>
    </div>
    <div id="mask"></div>
</div>
	<?php
		include_once '../../controllers/SesionController.php';
		$misesion = new SesionController();
		$misesion->sesionIniciada(1);
		$misesion->sesionTerminada();
	?>
		<div id="header-bg"></div>
		<div id="page">
			<div id="header">
				<div id="logo"></div>
				<div id="nav-bar">
				<form method="post" action="">
					<ul>
						<li><a href="#dialog" name="modal">Crear un test</a></li>
						<li><a href="cronestudiante.phtml">Cronograma</a></li>
						<li><a href="#">Mi Rendimiento</a></li>
						<li><input class="boton_salir" type="submit" name="logout" id ="logout" value="Salir"/></li>
					</ul>
					</form>
				</div>
			</div>
			<div id="banner">
				<div id="image-banner"></div>
				<div id="motd"></div>
			</div>
			<div id="content" style="height: 480px;">
				<div class="help"></div>
				<div id="login-info">
					<p><?php echo "" . $_SESSION['nombres'] . " ". $_SESSION['apellidos'] . "[estudiante]"?></p>
				</div>
				<div id="menubanner"></div>
				<div id="options">				
					<table>
						<tr>
							<td align="center">
								<a href="#dialog" name="modal"><img src="../images/add_page.png" height="48" width="48"/>
								<p>Crear un test</p></a>
							</td>
							<td align="center">
								<a href="cronestudiante.phtml"><img src="../images/cron.png" height="48" width="48"/>
								<p>Cronograma</p></a>
							</td>
						</tr>
						<tr>
							<td align="center">
								<a href="#"><img src="../images/chart.png" height="48" width="48"/>
								<p>Mi Rendimiento</p></a>
							</td>
							<td align="center">
								<a href="javascript:;" onclick="logout();"><img src="../images/quit.png" height="48" width="48"/>
								<p>Salir</p></a>
							</td>
						</tr>
					</table>
				</div>
			
			<div id="sidebar">
				<div id="resumencron">
					<p class="title">Pr&oacute;ximos eventos:</p>
					<ul>
						<li><p><span class="fecha">Mayo 6</span> Simulacro 1 sajkkjsadjksadsaj klsa klsalkd ksalkds</p></li>
						<li><p><span class="fecha">Mayo 26</span> Simulacro 2 asjdnasjdh </p></li>
						<li><p><span class="fecha">Junio 2</span> Simulacro 3 djasjdsl jsjksahd sakdsjkhda sadkshadjks </p></li>
					</ul>
				</div>
				<div id="resumenrendimiento">
					<p class="title">Estadísticas:</p>
					<ul>
						<li><p><span class="item">Preguntas correctas:</span> 76 / 100</p></li>
						<li><p><span class="item">Porcentaje:</span> 76%</p></li>
						<li><p><span class="item">Ranking:</span> 1°</p></li>
					</ul>
				</div>
			</div>
			</div>
			<div id="footer">
				<p>&copy; 2011 Universidad de C&oacute;rdoba</p>
			</div>
		</div>
			</body>
</html>
