<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title>&Eacute;cesis :: Sistema para la simulaci&oacute;n de la evaluacion ECAES</title>
		<link rel="stylesheet" href="../css/reset.css" media="screen"/>
		<link rel="stylesheet" href="../css/style.css" media="screen"/>
		<script src="../js/usuario.js" type="text/javascript"></script>
		<script src="../js/redirecciones.js" type="text/javascript"></script>
	</head>
	<body>
	<?php
		include_once '../../controllers/SesionController.php';
		$misesion = new SesionController();
		$misesion->sesionIniciada(4);
		$misesion->sesionTerminada();
	?>
		<div id="header-bg"></div>
		<div id="page">
			<div id="header">
				<div id="logo"></div>
				<div id="nav-bar">
				<form method="post" action="">
					<ul>
						<li><a href="#">Usuarios</a></li>
						<li><a href="#">Asignaturas</a></li>
						<li><a href="#">Dependencias</a></li>
						<li><input class="boton_salir" type="submit" name="logout" id ="logout" value="Salir"/></li>
					</ul>
					</form>
				</div>
			</div>
			<div id="banner">
				<div id="image-banner"></div>
				<div id="motd"></div>
			</div>
			<div id="content" style="height: 400px;">
				<div class="help"></div>
				<div id="login-info">
					<p><?php echo "" . $_SESSION['nombres'] . " ". $_SESSION['apellidos'] . "[administrador]"?></p>
				</div>
				<div id="menubanner"></div>
				<div id="options">				
					<table>
						<tr>
							<td align="center">
								<a href="#"><img src="../images/users.png" height="48" width="48"/>
								<p>Gesti&oacute;n de usuarios</p></a>
							</td>
							<td align="center">
								<a href="#"><img src="../images/office_folders.png" height="48" width="48"/>
								<p>Gesti&oacute;n de asignaturas</p></a>
							</td>
						</tr>
						<tr>
							<td align="center">
								<a href="#"><img src="../images/rendimiento.jpg" height="48" width="48"/>
								<p>Gesti&oacute;n de dependencias</p></a>
							</td>
							<td align="center">
								<a href="javascript:;" onclick="logout();"><img src="../images/quit.png" height="48" width="48"/>
								<p>Salir</p></a>
							</td>
						</tr>
					</table>
				</div>
			</div>
			<div id="sidebar">
				
			</div>
			<div id="footer">
				<p>&copy; 2011 Universidad de C&oacute;rdoba</p>
			</div>
		</div>
			</body>
</html>
