<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
		<title>&Eacute;cesis :: Sistema para la simulaci&oacute;n de la evaluacion ECAES</title>
		<link rel="stylesheet" href="../css/reset.css" media="screen"/>
		<link rel="stylesheet" href="../css/registro.css" media="screen"/>
		<link rel="stylesheet" href="../css/style.css" media="screen"/>
		<script src="../jquery/jquery-1.5.js" type="text/javascript"></script>
		<script src="../js/usuario.js" type="text/javascript"></script>
		<script src="../js/redirecciones.js" type="text/javascript"></script>
		<script src="../js/calendariofecha.js" type="text/javascript"></script>
	</head>
	<body>
	<?php 
		include_once '../../controllers/UserController.php';
		$alta = new UserController();
		$alta->registerActions();
	?>
	<div id="header-bg"></div>
		<div id="page">
			<div id="header">
				<div id="logo"></div>
			</div>
			<div id="banner">
				<div id="image-banner"></div>
				<div id="motd"></div>
			</div>
	
		<div id="contenedor">
		
			<h2>Formulario de Registro</h2>
			<form method="post" action="#">
			<ul>
			
			<li class="derecha">
				<label class="titulo" for="identificaion">Identificación<span class="requerido">*</span></label>
				<div>
					<span class="tercio">
						<select id="tipodoc" name="tipodoc">
							<option value="TI">Tarjeta de identidad</option>
							<option value="CC" selected="selected">Cedula de ciudadania</option>
							<option value="CE">Cedula de extranjeria</option>
						</select>
						<label for="tipodoc">Tipo de identificación</label>
					</span>
					
					<span class="tercio">
						<input id="identificacion" name="identificacion" value="" />
						<label for="identificacion">Numero identificacion</label>
					</span>
				</div>
				<p class="ayuda">Asegúrate de escribir correctamente tu número de id.</p>
			</li>
			
			<li class="izquierda">
				<label class="titulo" for="nombres">Nombre, apellidos y genero<span class="requerido">*</span>
				</label>
			<div>
			<span class="completo">
				<input id="nombres" name="nombres" value="" />
				<label for="nombres">Nombres</label>
			</span>
			
			<span class="completo">
				<input id="apellidos" name="apellidos" value="" />
				<label for="apellidos">Apellidos</label>
			</span>
			
			<span class="tercio">
						<select id="genero" name="genero">
							<option value=""></option>
							<option value="M">Masculino</option>
							<option value="F">Femenino</option>
						</select>
						<label for="genero">genero</label>
			</span>
			</div>
			
			<p class="ayuda">No te olvides de escribir tambien tu segundo apellido</p>
			</li>
			
			<li class="derecha">
				<label class="titulo" for="usuario">usuario y contraseña<span class="requerido">*</span>
				</label>
			<div>
			<span class="completo">
				<input id="usuario" name="usuario" value="" />
				<label for="usuario">Escriba su nombre de usuario</label>
			</span>
			
			<span class="completo">
				<input id="contrasenia1" name="contrasenia1" value="" />
				<label for="contrasenia1">Contraseña</label>
			</span>
			
			<span class="completo">
				<input id="contrasenia2" name="contrasenia2" value="" />
				<label for="contrasenia2">Confirmar contraseña</label>
			</span>
			</div>
			
			<p class="ayuda">La contraseña debe tener al menos 8 caracteres, mayuscula, minuscula y un numero</p>
			</li>
			
			<li class="izquierda">
				<label class="titulo" for="fechanacimiento">Fecha de nacimiento <span class="requerido">*</span></label>
				<div>
					
					<span class="tercio">
						<input id="fecha" name="fecha" readonly="readonly" type="text" size="25"><a href="javascript:NewCal('fecha','yyyymmdd')"><img src="../images/cal.gif" width="16" height="16" border="0" alt="Pick a date"></a>
						<label for="cal1Date">Fecha de nacimiento(aaa-mm-dd)</label>
					</span>
					<div id="cal1Container"></div>  			
				</div>
				<p class="ayuda">Seleccione su fecha de nacimiento de la lista.</p>
				</li>
			
			<li class="derecha">
				<label class="titulo" for="direccion">Direccion<span class="requerido">*</span> </label>
				
				<div>
					<span class="completo">
						<input id="direccion" name="direccion" value="" />
						<label for="direccion">Dirección residencia</label>
					</span>
					
					<span class="completo">
						<input id="municipio" name="municipio" value="" />
						<label for="municipio">Municipio</label>
					</span>
					
					<span class="tercio">
						<select id="departamento" name="departamento">
							<option value=""></option>
							<option value="Cordoba">Cordoba</option>
							<option value="Sucre">Sucre</option>
							<option value="Atlantico">Atlantico</option>
						</select>
						<label for="provincia">Departamento</label>
					</span>
					
					<span class="dostercios">
						<select id="pais" name="pais">
							<option value=""></option>
							<option value="Colombia">Colombia</option>
							<option value="Venezuela">Venezuela</option>
							<option value="Ecuador">Ecuador</option>
						</select>
						<label for="pais">País</label>
					</span>
				</div>
				
				<p class="ayuda">Escriba la direccion en la que vive mientras asiste a sus clases universitarias.</p>
			</li>
			
			<li class="izquierda">
				<label class="titulo" for="email">Email<span class="requerido">*</span></label>
				<div>
					<span class="completo">
						<input id="email" name="email" value="" />
					</span>
				</div>
				<p class="ayuda">Asegúrate de que sea válido</p>
			</li>
			
			<li class="derecha">
				<label class="titulo" for="telefonofijo">Teléfono <span class="requerido">*</span></label>
				<div>
				
					<span class="mitad">
						<input id="telefonofijo" name="telefonofijo" value="" />
						<label for="telefonofijo">Fijo</label>
					</span>
					
					<span class="mitad">
						<input id="telefonomovil" name="telefonomovil" value="" />
						<label for="telefonomovil">Móvil</label>
					</span>
				</div>
				<p class="ayuda">Sin prefijo de país y sin espacios en blanco</p>
				</li>
			
				<li class="izquierda">
				<label class="titulo" for="universidad">Universidad <span class="requerido">*</span></label>
				<div>
				
					<span class="tercio">
						<input id="codigoregistro" name="codigoregistro" value="" />
						<label for="codigoregistro">Código de registro</label>
					</span>
					
					<span class="tercio">
						<select id="programa" name="programa">
							<option value=""></option>
							<option value="1">Ingenieria de Sistemas</option>
							<option value="2">Ingenieria Industrial</option>
							<option value="3">Ingenieria Mecanica</option>
							<option value="4">Ingenieria Ambiental</option>
						</select>
						<label for="programa">Programa al que pertenece</label>
					</span>
					
					<span class="tercio">
						<select id="rol" name="rol">
							<option value=""></option>
							<option value="1">Estudiante</option>
							<option value="2">Docente</option>
						</select>
						<label for="rol">Rol del usuario</label>
					</span>
				</div>
				<p class="ayuda">Si no posee un codigo de registro dirijase a su departamente y solicitelo.</p>
				</li>
			
				<li class="botones">
					<input id="alta" name="alta" type="submit" value="Darme de alta &rarr;" />
				</li>
				
			
			</ul>
			</form>
		</div>
		<div id="footer">
			<p>&copy; 2011 Universidad de C&oacute;rdoba</p>
		</div>
		</div>
	</body>
</html>
